server:
  port: 8888

eureka:
  instance:
    metadata-map:
      zone: zone-1
  client:
    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    prefer-same-zone-eureka: true
    region: gd
    availability-zones:
      gd: zone-1,zone-2,zone-3
    service-url:
      zone-1: http://s1.cn:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/hy9902/springCloudConfig.git"
          search-paths: /**
          username: hy9902
          password: "{cipher}ec6d9d84a00ee55a91513e223614e91702346207a2b573c6da6ea756d1747fd72cbe9d55be569b393e88f2240cdafa0c"
      label: master

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
