server:
  port: 8800

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
spring:
  security:
    user:
      name: user
      password: hy9902
  redis:
    host: 127.0.0.1
    port: 6379