server:
  port: 9000


eureka:
  instance:
    metadata-map:
      zone: zone-2
  client:
    fetch-registry: true
    service-url:
      zone-2:  http://s2.cn:8762/eureka/
    region: gd
    register-with-eureka: true
    prefer-same-zone-eureka: true
    availability-zones:
      gd: zone-1,zone-2,zone-3
#    healthcheck:
#      enabled: true


logging:
  level:
    root: info

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    shutdown:
#      enabled: true
#    health:
#      show-details: always
spring:
  security:
    user:
      name: user
      password: hy9902
      roles: SUPERADMIN
  redis:
    host: 119.29.74.11
    port: 6379
  profiles:
    active: dev

