eureka:
  instance:
    instance:
      appname: eureka
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    prefer-same-zone-eureka: true
    region: gd
    availability-zones:
      gd: zone-1,zone-2,zone-3
  environment: default
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

info:
  author: hydt
---
server:
  port: 8761

eureka:
  instance:
    hostname: s1.cn
  client:
    service-url:
      zone-1: http://s1.cn:8761/eureka/
      zone-2: http://s2.cn:8762/eureka/
      zone-3: http://s3.cn:8763/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

spring:
  profiles: s1
info:
  age: 18
---
spring:
  profiles: s2
info:
  age: 19
server:
  port: 8762

eureka:
  instance:
    hostname: s2.cn
  client:
    service-url:
      zone-1: http://s1.cn:8761/eureka/
      zone-2: http://s2.cn:8762/eureka/
      zone-3: http://s3.cn:8763/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
---
spring:
  profiles: s3
info:
  age: 20

server:
  port: 8763

eureka:
  instance:
    hostname: s3.cn
  client:
    service-url:
      zone-1: http://s1.cn:8761/eureka/
      zone-2: http://s2.cn:8762/eureka/
      zone-3: http://s3.cn:8763/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
---